[package]
name = "lieutenant_parser"
version = "0.1.0"
authors = ["Miro Andrin <miro.sveits@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex-syntax = "0.6"